#!/bin/bash
export PATH="~/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:/usr/local/share/npm/bin"
export PATH=$(brew --prefix ruby)/bin:$PATH
export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
export PATH="$(brew --prefix php56)/bin:$PATH"
export PATH="$PATH:/usr/local/share/python"

export EDITOR="vim"
export MANPAGER="less -X"
export LESS_TERMCAP_md="$ORANGE"

export LC_ALL="es_ES.UTF-8"
export LANG="es_ES"

export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"
