---
- homebrew_tap:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    url: "{{ item.url|default(omit) }}"
  with_items: "{{ brew_taps|difference(brew_taps_excludes) }}"
- homebrew:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    options: "{{ item.options|default(omit) }}"
  with_items: "{{ brew_packages|difference(brew_excludes) }}"
- homebrew_cask:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    options: "{{ item.options|default(omit) }}"
  with_items: "{{ cask_packages|difference(cask_excludes) }}"
- npm:
    name: "{{ item.name|default(item) }}"
    global: "{{ item.global|default('yes') }}"
  with_items: "{{ npm_packages|difference(npm_excludes) }}"
- pear:
    name: "{{ item.name|default(item) }}"
  with_items: "{{ pear_packages|difference(pear_excludes) }}"
- pip:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    version: "{{ item.version|default(omit) }}"
    extra_args: "{{ item.extra_args|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
    requirements: "{{ item.requirements|default(omit) }}"
  with_items: "{{ pip_packages|difference(pip_excludes) }}"
- gem:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    version: "{{ item.version|default(omit) }}"
    gem_source: "{{ item.gem_source|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
    pre_release: "{{ item.pre_release|default(omit) }}"
    repository: "{{ item.repository|default(omit) }}"
  with_items: "{{ gem_packages|difference(gem_excludes) }}"
