---
- name: Copy docker aliases
  template: src=templates/aliases/docker.sh dest=~/.zsh/aliases/docker.sh
- name: Copy gitlab aliases
  template: src=templates/aliases/gitlab.sh dest=~/.zsh/aliases/gitlab.sh
- name: Copy k8s
  template: src=templates/aliases/gitlab.sh dest=~/.zsh/aliases/k8s.sh

# autoload -U +X compinit && compinit
# autoload -U +X bashcompinit && bashcompinit

# vagrant plugin install vagrant-hostsupdater

# Privoxy /usr/local/etc/privoxy/config
# forward-socks5   /               127.0.0.1:9050 .

# vagrant plugin install vagrant-hostsupdater
# vagrant plugin install vagrant-hostmanager
## Add to playbook /etc/sudoers
# # Allow passwordless startup of Vagrant with vagrant-hostsupdater.
# Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
# Cmnd_Alias VAGRANT_HOSTS_REMOVE = /usr/bin/sed -i -e /*/ d /etc/hosts
# %admin ALL=(root) NOPASSWD: VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
