---
default_npm_packages:
  - letsencrypt-cli
default_brew_packages:
  - helmfile
  - kubernetes-cli
  - kubernetes-helm
  - python3
  - certbot
  - dehydrated
  - ruby
  - s3cmd
  - libmaxminddb
  - tor
  - privoxy
default_gem_packages: []
  # - librarian-chef
  # - knife-solo
  # - capistrano
default_pip_packages:
  - awscli
  - docker-compose
default_cask_packages:
  - virtualbox
  - vagrant
  - docker
