- name: extensions for vscode
  shell: code --install-extension {{ item }}
  register: vscode_result
  changed_when: "'was successfully installed' in vscode_result.stdout"
  with_items:
    - "{{ default_vscode_packages }}"

# $ cd /Applications/Utilities/Terminal.app/Contents/Resources/Fonts/
# $ cp *.otf ~/Library/Fonts/
