
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git git-extra symfony2)
source $ZSH/oh-my-zsh.sh

# Paths
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:/usr/local/share/npm/bin"
export PATH="$PATH:/usr/local/opt/ruby/bin"
export PATH="$PATH:/Users/$USER/.gem/ruby/2.3.0/bin"
export PATH="$PATH:/usr/local/opt/php56/bin"
export PATH="$PATH:/usr/local/share/python"

## Common envs
export VISUAL=vim
export EDITOR="$VISUAL"

## Source all environment files
for f in ~/.env_*; do
   . $f
done

## Source all aliases
for f in ~/.zsh/aliases/*; do
   . $f
done
