---
galaxy_info:
  author: Luis Hdez <luis.munoz.hdez@gmail.com>
  description: ~
  company: wobblecode
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: MacOSX
    versions:
    - 10.11
    - 10.12
    - 10.13
    - 10.14
  categories:
    - developer
    - packaging
    - vscode
dependencies:
  - role: ansible-macos.packages
    npm_packages: "{{ default_npm_packages }}"
    brew_packages: "{{ default_brew_packages }}"
    cask_packages: "{{ default_cask_packages }}"
